#!/usr/bin/env bash

set -e  # Exit on any error

fail() {
    echo "Error: $1" >&2
    exit 1
}

# Get GOROOT using `go env`
GOROOT=$(go env GOROOT)
if [ $? -ne 0 ]; then
    fail "Failed to get GOROOT"
fi

# Get the path to the zoneinfo.zip
ZIPNAME="$GOROOT/lib/time/zoneinfo.zip"
if [ ! -f "$ZIPNAME" ]; then
    fail "zoneinfo.zip not found at $ZIPNAME"
fi

# Open the output file
GOFILE=${GOFILE:-"timezones.go"}
GOFILE="$(basename "$GOFILE" ".go")_generated.go"
if ! touch "$GOFILE"; then
    fail "Failed to create output file $GOFILE"
fi

# Write the generated code header
{
    echo "// Code generated by \"$(basename "${BASH_SOURCE[0]}")\""
    echo ""
    echo "package ${GOPACKAGE:-main}"
    echo ""
    echo "var TimeZones = []string{"
} > "$GOFILE"

# List the contents of the zip file and append them to the output file
if ! unzip -Z1 "$ZIPNAME" | while read -r path; do
    echo "    \"${path//Etc\//}\"," >> "$GOFILE"
done; then
    fail "Failed to process zip file $ZIPNAME"
fi

# Close the Go array
echo "}" >> "$GOFILE"

echo "TimeZones list generated successfully in $GOFILE."
