version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
  settings:
    gosec:
      excludes:
        - G204
        - G301
        - G302
        - G304
        - G306
        - G601
        - G101
      config:
        global:
          nosec: true
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA1029
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
